{ conditions: [
  {
    name: 'Blinded',
    source_text: 'Core Rulebook pg. 618',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'You can no longer see.',
    description_long: "You can’t see. All normal terrain is difficult terrain to you. You can’t detect anything using vision. You automatically critically fail Perception checks that require you to be able to see, and if vision is your only precise sense, you take a –4 status penalty to Perception checks. You are immune to visual effects. Blinded overrides dazzled.",
    other_conditions: false,
    always_value: false,
    effect_skill: true,
    effect_ability_score: false,
    situational: true,
    flat_check: false,
  },
  {
    name: 'Clumsy',
    source_text: 'Core Rulebook pg. 618',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'Your movements become clumsy and inexact.',
    description_long: "Your movements become clumsy and inexact. Clumsy always includes a value. You take a status penalty equal to the condition value to Dexterity-based checks and DCs, including AC, Reflex saves, ranged attack rolls, and skill checks using Acrobatics, Stealth, and Thievery.",
    other_conditions: false,
    always_value: true,
    effect_skill: true,
    effect_ability_score: true,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Concealed',
    source_text: 'Core Rulebook pg. 618',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'Other creatures have trouble perceiving you.',
    description_long: "While you are concealed from a creature, such as in a thick fog, you are difficult for that creature to see. You can still be observed, but you’re tougher to target. A creature that you’re concealed from must succeed at a DC 5 flat check when targeting you with an attack, spell, or other effect. Area effects aren’t subject to this flat check. If the check fails, the attack, spell, or effect doesn’t affect you.",
    other_conditions: false,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: true,
    flat_check: true,
  },
  {
    name: 'Confused',
    source_text: 'Core Rulebook pg. 618',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'You can no longer tell friend from foe.',
    description_long: "You don’t have your wits about you, and you attack wildly. You are flat-footed, you don’t treat anyone as your ally (though they might still treat you as theirs), and you can’t Delay, Ready, or use reactions. \n\nYou use all your actions to Strike or cast offensive cantrips, though the GM can have you use other actions to facilitate attack, such as draw a weapon, move so that a target is in reach, and so forth. Your targets are determined randomly by the GM. If you have no other viable targets, you target yourself, automatically hitting but not scoring a critical hit. If it’s impossible for you to attack or cast spells, you babble incoherently, wasting your actions. \n\nEach time you take damage from an attack or spell, you can attempt a DC 11 flat check to recover from your confusion and end the condition.",
    other_conditions: true,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: true,
    flat_check: true,
  },
  {
    name: 'Controlled',
    source_text: 'Core Rulebook pg. 618',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You've lost control of your actions.",
    description_long: "Someone else is making your decisions for you, usually because you’re being commanded or magically dominated. The controller dictates how you act and can make you use any of your actions, including attacks, reactions, or even Delay. The controller usually does not have to spend their own actions when controlling you.",
    other_conditions: false,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Dazzled',
    source_text: 'Core Rulebook pg. 618',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'You have trouble seeing.',
    description_long: "Your eyes are overstimulated. If vision is your only precise sense, all creatures and objects are concealed from you.",
    other_conditions: true,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: false,
    flat_check: true,
  },
  {
    name: 'Deafened',
    source_text: 'Core Rulebook pg. 619',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You can't hear.",
    description_long: "You can’t hear. You automatically critically fail Perception checks that require you to be able to hear. You take a –2 status penalty to Perception checks for initiative and checks that involve sound but also rely on other senses. If you perform an action with the auditory trait, you must succeed at a DC 5 flat check or the action is lost; attempt the check after spending the action but before any effects are applied. You are immune to auditory effects.",
    other_conditions: false,
    always_value: false,
    effect_skill: true,
    effect_ability_score: false,
    situational: true,
    flat_check: true,
  },
  {
    name: 'Doomed',
    source_text: 'Core Rulebook pg. 619',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'You are unnaturally close to death.',
    description_long: "A powerful force has gripped your soul, calling you closer to death. Doomed always includes a value. The dying value at which you die is reduced by your doomed value. If your maximum dying value is reduced to 0, you instantly die. When you die, you’re no longer doomed.\n\nYour doomed value decreases by 1 each time you get a full night’s rest.",
    other_conditions: false,
    always_value: true,
    effect_skill: false,
    effect_ability_score: false,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Drained',
    source_text: 'Core Rulebook pg. 619',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "Some of your life force has been removed.",
    description_long: "When a creature successfully drains you of blood or life force, you become less healthy. Drained always includes a value. You take a status penalty equal to your drained value on Constitution-based checks, such as Fortitude saves. You also lose a number of Hit Points equal to your level (minimum 1) times the drained value, and your maximum Hit Points are reduced by the same amount. For example, if you’re hit by an effect that inflicts drained 3 and you’re a 3rd-level character, you lose 9 Hit Points and reduce your maximum Hit Points by 9. Losing these Hit Points doesn’t count as taking damage.\n\nEach time you get a full night’s rest, your drained value decreases by 1. This increases your maximum Hit Points, but you don’t immediately recover the lost Hit Points.",
    other_conditions: false,
    always_value: true,
    effect_skill: false,
    effect_ability_score: true,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Dying',
    source_text: 'Core Rulebook pg. 619',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You're on death's doorstep.",
    description_long: "You are bleeding out or otherwise at death’s door. While you have this condition, you are unconscious . Dying always includes a value, and if it ever reaches dying 4, you die. If you’re dying, you must attempt a recovery check at the start of your turn each round to determine whether you get better or worse. Your dying condition increases by 1 if you take damage while dying, or by 2 if you take damage from an enemy’s critical hit or a critical failure on your save.\n\nIf you lose the dying condition by succeeding at a recovery check and are still at 0 Hit Points, you remain unconscious, but you can wake up as described in that condition. You lose the dying condition automatically and wake up if you ever have 1 Hit Point or more. Any time you lose the dying condition, you gain the wounded 1 condition, or increase your wounded condition value by 1 if you already have that condition.",
    other_conditions: true,
    always_value: true,
    effect_skill: false,
    effect_ability_score: false,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Encumbered',
    source_text: 'Core Rulebook pg. 619',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You're overburdened.",
    description_long: "You are carrying more weight than you can manage. While you’re encumbered, you’re clumsy 1 and take a 10-foot penalty to all your Speeds. As with all penalties to your Speed, this can’t reduce your Speed below 5 feet.",
    other_conditions: true,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Enfeebled',
    source_text: 'Core Rulebook pg. 619',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You're physically weakened.",
    description_long: "You’re physically weakened. Enfeebled always includes a value. When you are enfeebled, you take a status penalty equal to the condition value to Strength-based rolls and DCs, including Strength-based melee attack rolls, Strength-based damage rolls, and Athletics checks.",
    other_conditions: false,
    always_value: true,
    effect_skill: true,
    effect_ability_score: true,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Facinated',
    source_text: 'Core Rulebook pg. 619',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "Something forcefully caught your attention.",
    description_long: "You are compelled to focus your attention on something, distracting you from whatever else is going on around you. You take a –2 status penalty to Perception and skill checks, and you can’t use actions with the concentrate trait unless they or their intended consequences are related to the subject of your fascination (as determined by the GM). For instance, you might be able to Seek and Recall Knowledge about the subject, but you likely couldn’t cast a spell targeting a different creature. This condition ends if a creature uses hostile actions against you or any of your allies.",
    other_conditions: false,
    always_value: false,
    effect_skill: true,
    effect_ability_score: false,
    situational: true,
    flat_check: false,
  },
  {
    name: 'Fatigued',
    source_text: 'Core Rulebook pg. 620',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You're tired and can't summon much energy.",
    description_long: "You’re tired and can’t summon much energy. You take a –1 status penalty to AC and saving throws. While exploring, you can’t choose an exploration activity.\n\nYou recover from fatigue after a full night’s rest.",
    other_conditions: false,
    always_value: false,
    effect_skill: false,
    effect_ability_score: true,
    situational: true,
    flat_check: false,
  },
  {
    name: 'Flat-Footed',
    source_text: 'Core Rulebook pg. 620',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You're defenses have slipped.",
    description_long: "You’re distracted or otherwise unable to focus your full attention on defense. You take a –2 circumstance penalty to AC. Some effects give you the flat-footed condition only to certain creatures or against certain attacks. Others—especially conditions—can make you universally flat-footed against everything. If a rule doesn’t specify that the condition applies only to certain circumstances, it applies to all of them; for example, many effects simply say “The target is flat-footed.”",
    other_conditions: false,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: true,
    flat_check: false,
  },
  {
    name: 'Fleeing',
    source_text: 'Core Rulebook pg. 620',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: "You're compelled to run away.",
    description_long: "You’re forced to run away due to fear or some other compulsion. On your turn, you must spend each of your actions trying to escape the source of the fleeing condition as expediently as possible (such as by using move actions to flee, or opening doors barring your escape). The source is usually the effect or caster that gave you the condition, though some effects might define something else as the source. You can’t Delay or Ready while fleeing.",
    other_conditions: false,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: true,
    flat_check: false,
  },
  {
    name: 'Blinded',
    source_text: 'Core Rulebook pg. 620',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'You can no longer see.',
    description_long: "",
    other_conditions: false,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: false,
    flat_check: false,
  },
  {
    name: 'Blinded',
    source_text: 'Core Rulebook pg. 620',
    source_url: 'https://paizo.com/products/btq01y0k?Pathfinder-Core-Rulebook',
    description_short: 'You can no longer see.',
    description_long: "",
    other_conditions: false,
    always_value: false,
    effect_skill: false,
    effect_ability_score: false,
    situational: false,
    flat_check: false,
  },
  
]}